backend/modules/user/controllers/ReferralController.php
<?php

namespace backend\modules\user\controllers;

use yii\helpers\ArrayHelper;
use common\modules\profile\models\Profile;
use common\components\utils\DefaultMessage;
use common\components\utils\Text;
use common\modules\user\models\NewPasswordForm;
use common\modules\user\models\UserClient;
use Yii;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\data\ActiveDataProvider;
use common\modules\adminGw\models\Page;
use common\components\web\Controller;
use common\modules\user\models\User;
use mdm\admin\models\Assignment;
use function Webmozart\Assert\Tests\StaticAnalysis\null;

class ReferralController extends Controller {
    private $dataService;
    
    public function init() {
        $this->pageTitle = $this->getPageName(UserClient::class);
        $this->pageIdentifier = $this->getPageUrl(UserClient::class);
        $this->dataService = $this->dataService ?? Yii::$app->getModule('user')->get('userService');
        parent::init();
    }
    
    public function behaviors() {
        $permissionName = 'User';
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow'   => TRUE,
                        'roles'   => ["manage{$permissionName}", "create{$permissionName}", "update{$permissionName}", "delete{$permissionName}"],
                    ],
                    [
                        'actions' => ['create'],
                        'allow'   => TRUE,
                        'roles'   => ["manage{$permissionName}", "create{$permissionName}"],
                    ],
                    [
                        'actions' => ['update', 'change-password'],
                        'allow'   => TRUE,
                        'roles'   => ["manage{$permissionName}", "update{$permissionName}"],
                    ],
                    [
                        'actions' => ['delete'],
                        'allow'   => TRUE,
                        'roles'   => ["manage{$permissionName}", "delete{$permissionName}"],
                    ],
                    [
                        'actions' => ['clear-filter'],
                        'allow'   => TRUE,
                        'roles'   => ['@'],
                    ],
                ],
            ],
        ];
    }
    
    public function actionIndex() {
        $model = UserClient::find();
        $filter = Yii::$app->request->get();

        $filter = $this->manipulatingTheFilterInSession($filter);

        $dataProvider = new ActiveDataProvider([
            'query'      => $model->filter($filter),
            'pagination' => [
                'pageSizeLimit' => [1, 100],
            ],
        ]);

        return $this->render('index', ['dataProvider' => $dataProvider, 'filter' => $filter, 'pageTitle' => Text::pluralize($this->pageTitle)]);
    }
    
    public function actionUpdate($id) {
        $errors = [];
        $modelUser = User::find()->where(['IS', User::tableName() . '.deleted', NULL])->andWhere(['id' => $id])->one();
        if ($modelUser == NULL) {
            Yii::$app->session->setFlash('error', DefaultMessage::registerNotFound($this->pageTitle, 'o'));
            return $this->redirect(['index']);
        }
        $modelUserClient = UserClient::find()->andWhere(['>', 'user_client.status', -1])->all();
        
        $newPassword = new NewPasswordForm();
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            $modelUser->load($post);
            $modelUserClient->load($post);
            if (Yii::$app->request->get('validation', FALSE)) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $errors = array_merge($errors, ActiveForm::validate($modelUser));
                $errors = array_merge($errors, ActiveForm::validate($modelUserClient));
                return $errors;
            }
            
            if ($this->dataService->updateClient($modelUser, $modelUserClient)) {
                Yii::$app->session->setFlash('success', DefaultMessage::sucessOnUpdate($this->pageTitle, 'o'));
                $redirect = $this->redirectAfterSave($post['button_submit'] ?? $post['button_submit-and-back'], self::ACTION_UPDATE, 'user', $modelUser->id);
                return $this->redirect([$redirect]);
            } else {
                Yii::$app->session->setFlash('error', DefaultMessage::errorOnUpdate($this->pageTitle, 'o'));
                return $this->redirect(['user/update/' . $modelUser->id]);
            }
        } else {
            return $this->render('update', ['model' => $modelUser, 'modelUserClient' => $modelUserClient, 'newPassword' => $newPassword, 'pageTitle' => $this->pageTitle]);
        }
    }
    
    
}

backend/modules/user/controllers/UserController.php
<?php

namespace backend\modules\user\controllers;

use yii\helpers\ArrayHelper;
use common\modules\profile\models\Profile;
use common\components\utils\DefaultMessage;
use common\components\utils\Text;
use common\modules\user\models\NewPasswordForm;
use common\modules\user\models\UserClient;
use Yii;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\widgets\ActiveForm;
use yii\data\ActiveDataProvider;
use common\modules\adminGw\models\Page;
use common\components\web\Controller;
use common\modules\user\models\User;
use mdm\admin\models\Assignment;
use function Webmozart\Assert\Tests\StaticAnalysis\null;

class UserController extends Controller {
    private $dataService;
    
    public function init() {
        $this->pageTitle = $this->getPageName(UserClient::class);
        $this->pageIdentifier = $this->getPageUrl(UserClient::class);
        $this->dataService = $this->dataService ?? Yii::$app->getModule('user')->get('userService');
        parent::init();
    }
    
    public function behaviors() {
        $permissionName = 'User';
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow'   => TRUE,
                        'roles'   => ["manage{$permissionName}", "create{$permissionName}", "update{$permissionName}", "delete{$permissionName}"],
                    ],
                    [
                        'actions' => ['create'],
                        'allow'   => TRUE,
                        'roles'   => ["manage{$permissionName}", "create{$permissionName}"],
                    ],
                    [
                        'actions' => ['update', 'change-password'],
                        'allow'   => TRUE,
                        'roles'   => ["manage{$permissionName}", "update{$permissionName}"],
                    ],
                    [
                        'actions' => ['delete'],
                        'allow'   => TRUE,
                        'roles'   => ["manage{$permissionName}", "delete{$permissionName}"],
                    ],
                    [
                        'actions' => ['exportar'],
                        'allow'   => TRUE,
                        'roles'   => ['sysadmin'],
                    ],
                    [
                        'actions' => ['clear-filter'],
                        'allow'   => TRUE,
                        'roles'   => ['@'],
                    ],
                ],
            ],
        ];
    }
    
    public function actionIndex() {
        $model = UserClient::find()->orderBy(['created' => SORT_DESC]);
        
        $filter = Yii::$app->request->get();
        
        $filter = $this->manipulatingTheFilterInSession($filter);
        
        $dataProvider = new ActiveDataProvider([
            'query'      => $model->filter($filter),
            'pagination' => [
                'pageSizeLimit' => [1, 100],
            ],
        ]);
        
        return $this->render('index', ['dataProvider' => $dataProvider, 'filter' => $filter, 'pageTitle' => Text::pluralize($this->pageTitle)]);
    }
    
    public function actionUpdate($id) {
        $errors = [];
        $modelUser = User::find()->where(['IS', User::tableName() . '.deleted', NULL])->andWhere(['id' => $id])->one();
        if ($modelUser == NULL) {
            Yii::$app->session->setFlash('error', DefaultMessage::registerNotFound($this->pageTitle, 'o'));
            return $this->redirect(['index']);
        }
        $modelUserClient = UserClient::find()->andWhere(['user_id' => $id])->one();
        
        $newPassword = new NewPasswordForm();
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            $modelUser->load($post);
            $modelUserClient->load($post);
            if (Yii::$app->request->get('validation', FALSE)) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $errors = array_merge($errors, ActiveForm::validate($modelUser));
                $errors = array_merge($errors, ActiveForm::validate($modelUserClient));
                return $errors;
            }
            
            if ($this->dataService->updateClient($modelUser, $modelUserClient)) {
                Yii::$app->session->setFlash('success', DefaultMessage::sucessOnUpdate($this->pageTitle, 'o'));
                $redirect = $this->redirectAfterSave($post['button_submit'] ?? $post['button_submit-and-back'], self::ACTION_UPDATE, 'user', $modelUser->id);
                return $this->redirect([$redirect]);
            } else {
                Yii::$app->session->setFlash('error', DefaultMessage::errorOnUpdate($this->pageTitle, 'o'));
                return $this->redirect(['user/update/' . $modelUser->id]);
            }
        } else {
            return $this->render('update', ['model' => $modelUser, 'modelUserClient' => $modelUserClient, 'newPassword' => $newPassword, 'pageTitle' => $this->pageTitle]);
        }
    }
    
    public function actionDelete($id) {
        if ($this->dataService->deleteClient($id)) {
            Yii::$app->session->setFlash('success', DefaultMessage::sucessOnDelete($this->pageTitle, 'o'));
            return $this->redirect(['index']);
        } else {
            Yii::$app->session->setFlash('error', DefaultMessage::errorOnDelete($this->pageTitle, 'o'));
            return $this->redirect(['user/update/' . $id]);
        }
    }
    
    public function actionChangePassword($id) {
        $newPassword = new NewPasswordForm();
        
        if (Yii::$app->request->isPost) {
            $post = Yii::$app->request->post();
            $model = new NewPasswordForm();
            $model->load($post);
            
            if (Yii::$app->request->get('validation', FALSE)) {
                $errors = [];
                Yii::$app->response->format = Response::FORMAT_JSON;
                $errors = array_merge($errors, ActiveForm::validate($model));
                return $errors;
            }
        }
        
        $user = User::find()->andWhere(['id' => $id])->one();
        if ($this->dataService->recoveryUserPassword($newPassword, $user)) {
            Yii::$app->session->setFlash('success', 'Senha alterada com sucesso!');
            return $this->redirect(['user/update/' . $id]);
        } else {
            Yii::$app->session->setFlash('success', "Ocorreu um erro ao alterar a senha do {$this->pageTitle}!");
            return $this->redirect(['user/update/' . $id]);
        }
    }
    
    
    public function actionExportar() {
        
        $model = User::find()->innerJoin('user_client', 'user.id = user_client.user_id')->all();
        $this->layout = FALSE;
        return $this->render('exportar', ['sql' => $model]);
    }
    
}

backend/modules/user/views/referral/_form.php
<?php

use common\components\utils\CrudButton;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

$form = ActiveForm::begin([
    'id'                     => 'form',
    'options'                => [
        'class'                 => 'form_form',
        'data-redirect-success' => Url::to(['index'], TRUE),
        'data-readonly'         => $readonly ? 1 : 0,
    ],
    'validationUrl'          => Url::to([$model->isNewRecord ? 'create' : 'update', TRUE, 'validation' => TRUE, 'id' => $model->id]),
    'enableAjaxValidation'   => TRUE,
    'enableClientValidation' => FALSE,
    'validateOnSubmit'       => TRUE,
    'validateOnChange'       => FALSE,
    'validateOnBlur'         => FALSE,
]);
?>


<div class="form-content">
    <div class="form-fields">
        <div class="row">
            <div class="col">
                <?php echo $form->errorSummary($model, ['class' => 'alert alert-danger']); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="ibox">
                    <div class="ibox-title">
                        <h5>Informações</h5>
                    </div>
                    <div class="ibox-content">
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                <?= $form->field($model, 'name')->textInput(['class' => 'form-control form_field-input', 'maxlength' => TRUE, 'disabled' => TRUE]) ?>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                <?= $form->field($model, 'email')->textInput(['class' => 'form-control form_field-input', 'maxlength' => TRUE,'disabled' => TRUE]) ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                <?= $form->field($model, 'cpf')->textInput(['maxlength' => TRUE, 'data-mask' => '999.999.999-99', 'disabled' => TRUE]) ?>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-6">
                                <?= $form->field($model, 'cellphone')->textInput(['maxlength' => TRUE, 'data-mask' => '(99)99999-9999', 'disabled' =>TRUE]) ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="form-footer row m-0">
        <div class='d-flex bd-highlight col-12 p-0 m-0 dv-btn-actions'>
            <?php
            if (!$readonly) {
                $crudButton = new CrudButton();
                $crudButton->page = '/user/user/';
                $crudButton->model = $model;
                $crudButton->permissionsToUpdate = 'manageUser;updateUser';
                $crudButton->permissionsToDelete = 'manageUser;deleteUser';
                echo $crudButton->showCrudButtons($crudButton);
            }
            ?>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

backend/modules/user/views/referral/index.php
<?php

use common\components\utils\DefaultMessage;
use common\components\utils\Filter;
use common\components\utils\Text;
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\Breadcrumbs;
use yii\widgets\Pjax;
use common\modules\user\models\User;

$filterdButton = new Filter();
$this->title = 'Listagem de Indicações';
$this->params['breadcrumbs'][] = ['label' => $pageTitle];
$formName = substr($dataProvider->query->modelClass, strrpos($dataProvider->query->modelClass, '\\') + 1);
$formName = strtolower($formName);

$urlDefault = '/user/user';

$readonly = !(Yii::$app->user->can('sysadmin') || Yii::$app->user->can('manageUser'));

$fields = [
    'name'  => 'Nome',
    'email' => 'E-mail',
    'cpf'   => 'CPF',
];


$filter = empty($filter) ? [] : $filter;

?>
<div class="row wrapper border-bottom page-heading p-0">
    <div class="col-xs-12 col-sm-12 col-md-6 page-title">
        <h2><?= $this->title ?></h2>
    </div>
    <div class="breadcrumb col-xs-12 col-sm-12 col-md-6">
        <?php
        echo Breadcrumbs::widget([
            'tag'                => 'ol',
            'itemTemplate'       => "<li>{link}&nbsp;&nbsp;/&nbsp;&nbsp;</li>\n",
            'activeItemTemplate' => "<li class=\"active\"><strong>{link}</strong></li>\n",
            'links'              => $this->params['breadcrumbs'],
        ]);
        ?>
    </div>
</div>

<div class="row action-area">
    <div class="col-12 filter-area">
        <div class="row">
            <div class="col-12">
                <form id="options-form-<?= $formName ?>" method="GET" action="">
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-7 pb-2 col-lg-5 input-group">
                            <?= $filterdButton->showFilterField($fields, $filter) ?>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-2 pb-2">
                            <select class="input form-control filter-select" name="status" id="status">
                                <option value="">Status</option>
                                <?php foreach (User::$_status as $key => $status) {
                                    $field = !(isset($filter) && count($filter) > 0 && isset($filter['status'])) ? NULL : $filter['status']; ?>
                                    <option value="<?= $key; ?>" <?= $filterdButton->fieldSelected($field, $key); ?> >
                                        <?= $status; ?>
                                    </option>
                                <?php } ?>
                            </select>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-3 pb-2 pr-0 dv-filter">
                            <?= $filterdButton->showFieldButtons($urlDefault) ?>
                            <a href="<?= Url::to(['user/exportar'], true) ?>" class="btn btn-success btn-sm ml-2" style="color:#FFF;"><i class="far fa-file-excel" aria-hidden="true"></i> Excel </a>

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-sm-12">
            <div class="mail-box">
                <div class="row p-3 pt-0">
                    <div class="col-12 pt-0">
                        <?php
                        Pjax::begin([
                            'enablePushState'    => FALSE,
                            'enableReplaceState' => FALSE,
                            'formSelector'       => '#options-form-' . $formName,
                            'submitEvent'        => 'submit',
                            'timeout'            => 5000,
                            'clientOptions'      => ['maxCacheLength' => 0],
                        ]);
                        
                        echo GridView::widget([
                            'dataProvider' => $dataProvider,
                            'tableOptions' => [
                                'id'    => $formName . '-table',
                                'class' => 'table table-striped table-hover',
                            ],
                            'emptyText'    => '<div class="text-center">' . DefaultMessage::theSearchDidNotReturnData() . '</div>',
                            'layout'       => '{items}{pager}',
                            'options'      => [
                                'class'     => 'table-responsive',
                                'data-pjax' => TRUE,
                            ],
                            'columns'      => [
                                [
                                    'attribute'      => 'name',
                                    'label'          => 'Nome',
                                    'format'         => 'html',
                                    'enableSorting'  => TRUE,
                                    'headerOptions'  => [
                                        'class' => 'text-left',
                                        'style' => 'min-width:150px',
                                    ],
                                    'contentOptions' => ['class' => 'text-left'],
                                    'value'          => function ($data) use ($urlDefault) {
                                        return '<a href="' . Url::to([$urlDefault . "/update/" . $data->user_id], TRUE) . '" class="client-link">' . $data->userRel->name . '</a>';
                                    },
                                ],
                                [
                                    'attribute'      => 'email',
                                    'format'         => 'html',
                                    'enableSorting'  => TRUE,
                                    'headerOptions'  => [
                                        'class' => 'text-left',
                                        'style' => 'min-width:250px',
                                    ],
                                    'contentOptions' => ['class' => 'text-left'],
                                    'value'          => function ($data) use ($urlDefault) {
                                        return '<a href="' . Url::to([$urlDefault . "/update/" . $data->user_id], TRUE) . '" class="client-link">' . $data->userRel->email . '</a>';
                                    },
                                ],
                                [
                                    'attribute'      => 'referral_code',
                                    'label'          => 'Indicações',
                                    'format'         => 'html',
                                    'enableSorting'  => TRUE,
                                    'headerOptions'  => [
                                        'class' => 'text-left',
                                        'style' => 'min-width:150px',
                                    ],
                                    'contentOptions' => ['class' => 'text-left'],
                                    'value'          => function ($data) use ($urlDefault) {
                                        return '<a href="' . Url::to([$urlDefault . "/update/" . $data->user_id], TRUE) . '" class="client-link">' . $data->referral_code . '</a>';
                                    },
                                ],
                                
                                [
                                    'attribute'      => 'status',
                                    'label'          => 'Status',
                                    'format'         => 'html',
                                    'enableSorting'  => TRUE,
                                    'headerOptions'  => [
                                        'class' => 'text-left',
                                        'style' => 'min-width:200px',
                                    ],
                                    'contentOptions' => ['class' => 'text-left'],
                                    'value'          => function ($data) {
                                        if ($data->status == User::STATUS_PENDENT) {
                                            return '<i class="fas fa-user-clock color-status-pendent"></i> ' . User::$_status[$data->status];
                                        } else if ($data->status == User::STATUS_ACTIVE) {
                                            return '<i class="fas fa-user-check color-status-active"></i> ' . User::$_status[$data->status];
                                        }
                                    },
                                ],
                            ],
                        ]);
                        
                        Pjax::end();
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

backend/modules/user/views/referral/update.php
<?php

use yii\widgets\Breadcrumbs;
use yii\helpers\Url;

$this->title = 'Editar ' . $pageTitle;
$this->params['breadcrumbs'][] = ['label' => $pageTitle, 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$readonly = !(Yii::$app->user->can('sysadmin') || Yii::$app->user->can('manageUser') || Yii::$app->user->can('updateUser'));

?>
    <div class="row wrapper border-bottom page-heading p-0">
        <div class="col-xs-12 col-sm-12 col-md-6 page-title">
            <h2>
                <?= $this->title ?>
            </h2>
        </div>
        <div class="breadcrumb col-xs-12 col-sm-12 col-md-6">
            <?php
            echo Breadcrumbs::widget([
                'tag'                => 'ol',
                'itemTemplate'       => "<li>{link}&nbsp;&nbsp;/&nbsp;&nbsp;</li>\n",
                'activeItemTemplate' => "<li class=\"active\"><strong>{link}</strong></li>\n",
                'links'              => $this->params['breadcrumbs'],
            ]);
            ?>
        </div>
    </div>

<?= $this->renderAjax('_form', [
    'model'           => $model,
    'modelUserClient' => $modelUserClient,
    'newPassword'     => $newPassword,
    'readonly'        => $readonly
]) ?>